[package]
name = "rss_client"
version = "0.0.2"
authors = ["John Nagle <nagle@animats.com>"]

[dependencies]
hyper="*"
chrono="*"
RustyXML = "0.1.1"
unicode-segmentation = "0.1.2"

[[bin]]
name = "rss_client"



