[package]
name = "rss_client"
version = "0.0.4"
authors = ["John Nagle <nagle@animats.com>"]

[dependencies]
hyper = "0.14.9"
reqwest = { version = "0.11", features = ["blocking"] }
chrono="0.3.0"
RustyXML = "0.1.1"
unicode-segmentation = "0.1.2"
itertools="0.6.0"

[[bin]]
name = "rss_client"



