[package]
name = "rss_client"
version = "0.0.3"
authors = ["John Nagle <nagle@animats.com>"]

[dependencies]
hyper="0.10.9"
chrono="0.3.0"
RustyXML = "0.1.1"
unicode-segmentation = "0.1.2"

[[bin]]
name = "rss_client"



